### PR TITLE
Local secondary indexes

### PR DESCRIPTION
**Pull request by edpaget**
This is dependent on #21

### CODE REVIEW

**Comment by weavejester** [comment]
Please squash these commits down and remove commits unrelated to the pull request.

**Comment by edpaget** [comment]
I squashed commits, which included the one that did the v2 API update, since the creating the indexes were dependent on that. Did you intend for me to remove that commit entirely?

**Comment by edpaget** [comment]
Ah sorry I figured out what I did incorrectly. It'll be fixed shortly.

**Comment by edpaget** [comment]
I think it's all sorted out. Sorry for my sometimes poor git skills.

**Comment by weavejester** [comment]
No problem. Sorry for taking so long to find the time to review this properly.

**Pull request merged**
