### PR TITLE
Removing a chatty println

### PR DESCRIPTION
**Pull request by jarohen**
Hi James - quick pull request to remove a println in the result-map fn

James

### CODE REVIEW

**Comment by sheldonkwok** [comment]
Is this change reflected in the package? I still have a println there from 0.4.0.

**Comment by jarohen** [comment]
Hi James, hope you're keeping well!

When you get a moment, could you release this change? Cheers :)

James

**Comment by weavejester** [comment]
Released. Sorry for taking so long.

**Comment by jarohen** [comment]
Thanks :)

**Pull request merged**
