### PR TITLE
Feature/can update dynamo items

### PR DESCRIPTION
**Pull request by mrgordon**
This adds update functionality for Dynamo tables using a similar syntax as for range queries.

### CODE REVIEW

**Comment by mrgordon** [comment]
I would merge the range query pull request first so you only see the diffs against that here. I reused the normalize-operator function so I couldn't make them entirely separate pulls.

**Comment by weavejester** [comment]
I've merged your other pull request (thanks for that). Could you make sure this one is rebased off of the new master? It looks like there's some duplication here.

**Comment by mrgordon** [comment]
Merged over your master so the diff is sane now. Thanks for merging the other pull request!

**Comment by weavejester** [comment]
Could you rebase instead of merging? It looks like there's only one commit of note to this patch.

**Comment by mrgordon** [comment]
Sure, it's consolidated now.

**Comment by weavejester** [comment]
Thanks! The commit is a lot clearer and neater now :)

However, I found the `update-item` function a little hard to read:

``` clojure
(update-item cred "table" 36 nil "awesome" `(add 20) "updated" `(put 1339529420))
```

I think in-lining the update map makes it harder to understand what's going on. Instead, if we had:

``` clojure
(update-item cred "table" 36 nil {"awesome" `(add 20) "updated" `(put 1339529420)})
```

I think that makes it more obvious that these are keys relating to values. It also means that we can get rid of the `nil` when there isn't a range key:

``` clojure
(update-item cred "table" 36 {"awesome" `(add 20) "updated" `(put 1339529420)})
```

Because with the range key there would be 5 arguments, and without there's only 4.

We might also want to wrap each key in `name` so we could do:

``` clojure
(update-item cred "table" 36 {:awesome `(add 20) :updated `(put 1339529420)})
```

What do you think?

**Comment by mikeflynn** [comment]
This is is a great feature, but I still don't see it in the source.

**Comment by weavejester** [comment]
> This is is a great feature, but I still don't see it in the source.

This commit has not been merged because there was no response to the changes outlined in my last comment.

**Pull request closed without merging**
